name: Publish Allure Report to GitHub Pages

on:
  workflow_run:
    workflows: ['Playwright Tests']
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
          run-id: ${{ github.event.workflow_run.id }} # ← tells it WHERE to look
          github-token: ${{ secrets.GITHUB_TOKEN }} # ← authorises cross-workflow access

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
